window.dialogr=function(h){function S(a,c){var b,d=c.config;b={type:"button",id:a.idPrefix+"btn-"+M(c.key)};var e;d&&(e=c.config.text?d.text:"");e||(e=c.key);b=q("button",b);b.innerText=e;d["class"]&&w(b,d["class"]);d.close&&w(b,"close");d.updateFields&&w(b,"update-fields");return b}function M(a){null===a.match(/^[a-zA-Z]/)&&(a="a"+a);return a.replace(/[^a-zA-Z0-9-_]/,"").toLowerCase()}function n(a){var c=[],b;if(null===a)return[];if(Object.keys)c=Object.keys(a);else for(b in a)T.call(a,b)&&c.push(b);
return c}function t(a){return"function"===typeof a}function x(a,c){var b={},d,e,g;if(k(c))return a;e=n(a);for(g=0;g<e.length;g+=1)d=e[g],b[d]=a[d];e=n(c);for(g=0;g<e.length;g+=1)d=e[g],null==c[d]?delete b[d]:b[d]=c[d].constructor==Array?c[d]:"object"===typeof b[d]&&"object"===typeof c[d]?x(b[d],c[d]):c[d];if(2<arguments.length)for(g=2;g<arguments.length;g+=1)b=x(b,arguments[g]);return b}function q(a,c,b){var d;-1!==a.indexOf("#")&&(d=e.options.idPrefix+M(a.substr(a.indexOf("#")+1)),a=a.substr(0,a.indexOf("#")));
a=document.createElement(a);k(b)||p(a,b);k(c)||r(a,c);d&&r(a,{id:d});return a}function r(a,c){var b=n(c),d;if(!k(a))for(d=0;d<b.length;d+=1){var e=c[b[d]];k(e)||null===e?a.hasAttribute(b[d])&&a.removeAttribute(b[d]):a.setAttribute(b[d],e)}}function N(a,c){if(a.constructor==Array)for(var b=0;b<a.length;b++)N(a[b],c);else{var d=u(a);if(d)for(A[a]={},b=0;b<c.length;b+=1)A[a][c[b]]=v(d,c[b])}}function H(a){if(a.constructor==Array)for(var c=0;c<a.length;c+=1)H(a[c]);else(c=u(a))&&!k(A[a])&&p(c,A[a])}function p(a,
c){var b=n(c),d;if("undefined"!=typeof a)for(d=0;d<b.length;d+=1)a.style[b[d]]=c[b[d]]}function I(a,c){!0===c.button.close&&B()}function B(){e&&e.wrapper&&(J(document,"keydown",O),J(h,"resize",K),J(h,"wheel",P),e.wrapper.parentElement.removeChild(e.wrapper),e.overlay.parentElement.removeChild(e.overlay),e=null,H(["body","html"]))}function O(a){27==a.keyCode&&B()}function C(a,c,b){var d=e.options;t(d["make"+a])&&(c=d["make"+a]({elm:c}));c&&1===c.nodeType&&b.appendChild(c);return c}function P(a){a.preventDefault();
a.stopPropagation()}function U(a,c){if(a.attributes["class"]){var b=a.attributes["class"].value;if(b==c)return!0;for(var b=b.split(" "),d=0;d<b.length;d+=1)if(b.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")==c)return!0}return!1}function D(a,c,b){null==a||k(a)||(a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent?a.attachEvent("on"+c,b):a["on"+c]=b)}function J(a,c,b){null==a||k(a)||(a.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent?a.detachEvent("on"+c,b):a["on"+c]=null)}
function K(){var a=e.options,c=document.documentElement,b=Math.max(c.clientWidth,h.innerWidth||0),d=Math.max(c.clientHeight,h.innerHeight||0),c=a.width,f=a.height;null==a.width&&null==a.height||parseInt(a.width,10)>b||parseInt(a.height,10)>d?(c=b+"px",f=d+"px",w(e.wrapper,"dialogr-fullscreen"),p(u("body"),{"overflow-y":"hidden"}),p(u("html"),{"overflow-y":"hidden"})):(H(["body","html"]),r(e.wrapper,{"class":null}),"border-box"==v(e.wrapper,"box-sizing")?a=E(e.wrapper,!0):(a=l("border-width",e.wrapper),
a=F(a,l("padding",e.wrapper))),c=parseInt(c,10)-a.left-a.right+"px",f=parseInt(f,10)-a.top-a.bottom+"px");p(e.wrapper,{width:c,height:f,left:b/2-parseInt(c)/2+"px",top:d/2-parseInt(f)/2+"px"});E(e.wrapper);var d=E(e.content,!0),b=l("margin",e.content),a=l("margin",e.footer),g=l("margin",e.header);e.footer&&(d.bottom+=e.footer.offsetHeight);var m=0,k=0;e.header&&(m=e.header.offsetHeight);e.header&&(k=e.header.offsetTop);f=parseInt(f,10)-parseInt(m,10)-d.top-d.bottom;g=m+k+g.bottom;d=parseInt(c)-d.left-
d.right;f-=b.bottom+b.top+a.top+a.bottom;d-=b.left+b.right;m={top:0,bottom:0,right:0,left:0};"border-box"==v(e.wrapper,"box-sizing")&&(m=l("border-width",e.wrapper),m=F(m,l("padding",e.wrapper)),console.warn(l("padding",e.wrapper)),console.warn(l("margin",e.wrapper)),console.warn(l("border-width",e.wrapper)),d-=m.left+m.right,f-=m.top+m.bottom);p(e.content,{position:"absolute",width:d+"px",height:f+"px",top:g+"px"});e.footer&&(d=E(e.footer),p(e.footer,{width:parseInt(c)-d.left-d.right-a.left-a.right-
m.left-m.right+"px",top:g+e.content.offsetHeight+b.bottom+b.top+"px"}))}function w(a,c){r(a,{"class":c})}function E(a,c){if(!a)return{top:0,bottom:0,right:0,left:0};var b=l("padding",a);!0!==c&&(b=F(b,l("margin",a)));if("content-box"==v(a,"box-sizing"))b=F(b,l("border-width",a));else if("border-box"==v(a,"box-sizing"))return{top:0,bottom:0,right:0,left:0};return b}function F(a,c){var b=n(a),d;for(d=0;d<b.length;d++)a[b[d]]+=c[b[d]];return a}function l(a,c){var b={top:0,right:0,bottom:0,left:0};if(!c)return b;
b=v(c,a).split(" ");1==b.length?(b=parseInt(b[0],10),b={top:b,right:b,bottom:b,left:b}):b={top:parseInt(b[0],10),right:parseInt(b[1],10),bottom:parseInt(b[2],10),left:parseInt(b[3],10)};b.top=isNaN(b.top)?0:b.top;b.right=isNaN(b.right)?0:b.right;b.bottom=isNaN(b.bottom)?b.top:b.bottom;b.left=isNaN(b.left)?b.right:b.left;return b}function v(a,c){if(a.currentStyle)var b=a.currentStyle[c];else h.getComputedStyle&&(b=document.defaultView.getComputedStyle(a,null).getPropertyValue(c));return b}function u(a,
c){var b=null;c||(c=document);if("#"==a[0])b=document.getElementById(a.substr(1));else{if((b="."==a[0]?document.getElementsByClassName(a.substr(1)):c.querySelector(a))&&k(b.length))return b;b=0<b.length?b[0]:null}return b}function y(){return h.parent&&h.parent!=h&&h.parent.dialogr?h.parent.dialogr.isOpen():!1}function k(a){return"undefined"===typeof a}var T=Object.prototype.hasOwnProperty,Q={OK_BTN:"OK",CANCEL_BTN:"Cancel",CLOSE_BTN:"Close"},z,R,L={},G,e=null;L[Q.OK_BTN]=!0;L[Q.CANCEL_BTN]=!1;R={click:I,
idPrefix:"dialogr-",args:null,container:null,buttons:null,width:null,height:null,offsetWidth:0,offsetHeight:0,url:null,html:null,title:null,makeButton:null,wrapperTemplate:'<div id="{{id}}"></div>'};var A={};return{open:function(a){var c;c=Math.max(document.documentElement.clientHeight,h.innerHeight||0);var b=!1;N(["body","html"],["overflow-y"]);a&&a.footerTemplate&&(b=!0);a&&k(a.buttons)&&(a.buttons=L);a=x(R,a);e={options:a};if(a.buttons)for(d=n(a.buttons),c=0;c<d.length;c++)!0===a.buttons[d[c]]?
a.buttons[d[c]]={text:d[c],updateFields:!0,close:!0,click:I}:!1===a.buttons[d[c]]&&(a.buttons[d[c]]={text:d[c],close:!0,click:I});a.container||(c=document.getElementsByTagName("body"),a.container=1==c.length?c[0]:null);if(a.container){f=a.container;B();e.wrapper=q("div#wrapper",null,{visibility:"hidden",position:"fixed","z-index":50001});e.overlay=q("div#overlay",null,{visibility:"hidden","z-index":5E3});f.appendChild(e.overlay);f.appendChild(e.wrapper);a.title&&(c=q("div#header",null,{"overflow-y":"auto"}),
d=q("h1"),d.innerText=a.title,c.appendChild(d),e.header=C("Header",c,e.wrapper));a.html?e.content=C("Content",q("div#content",null,{"overflow-y":"auto"}),e.wrapper):a.url&&(e.content=C("Content",q("iframe#content",{src:a.url,frameborder:0}),e.wrapper));if(b||a.buttons)e.footer=q("div#footer",{"class":"buttons"},{position:"absolute"}),e.footer=C("Footer",e.footer,e.wrapper);if(a.buttons&&e.footer){var d=n(a.buttons),f=U(e.footer,"buttons")?e.footer:e.footer.getElementsByClassName("buttons");f.length&&
1==f.length&&(f=f[0]);if(f&&f.appendChild)for(c=0;c<d.length;c+=1){var b={key:d[c],config:a.buttons[d[c]],bindEvents:!0},g=S(e.options,b);t(a.makeButton)&&(b.elm=g,g=a.makeButton(b));if(!g||1!==g.nodeType){console&&console.error&&console.error("dialogr: makeButton must return a DOM Element");return}f.appendChild(g);g.dialogrButton=d[c].toString();a.buttons[d[c]]._runtime={elm:g};b.bindEvents&&D(g,"click",function(a){var b=e.options.buttons[a.target.dialogrButton],c={button:x(b,{_runtime:null})};!0===
b.updateFields&&t(z)&&(G=z());c.result=G;if(!0===c.button.updateFields&&e.options.fieldArgs){var d=n(e.options.fieldArgs),f;for(f=0;f<d.length;f++){var g=u(e.options.fieldArgs[d[f]]);if(!k(c.result[d[f]])){var h=c.result[d[f]];!g.tagName||"INPUT"!==g.tagName&&"SELECT"!==g.tagName&&"TEXTAREA"!==g.tagName||(g.attributes.type&&"checkbox"===g.attributes.type.value.toLowerCase()?g.checked=h:g.value=h)}}}t(b.click)?b.click(a,c):t(e.options.click)&&e.options.click(a,c);!0===b.close&&B()})}}p(e.overlay,{position:"fixed",
visibility:"visible","background-color":"rgba(0,0,0,0.5)",width:"100%",height:"100%","z-index":5E3,left:0,top:0},!0);K();D(h,"resize",K);p(e.wrapper,{visibility:"visible"});D(document,"keydown",O);D(h,"wheel",P)}else console&&console.warn&&console.warn("dialogr: Container was not found")},getArgs:function(){if(e){var a={},c=e.options,b,d,f;if(c.fieldArgs)for(b=n(c.fieldArgs),d=0;d<b.length;d++)if(f=u(c.fieldArgs[b[d]])){var g=a,k=b[d];f=!f.tagName||"INPUT"!==f.tagName&&"SELECT"!==f.tagName&&"TEXTAREA"!==
f.tagName?null:f.attributes.type&&"checkbox"===f.attributes.type.value.toLowerCase()?f.checked:f.value;g[k]=f}return x(c.args,a)}if(y())return h.parent.dialogr.getArgs()},updateDialogResult:function(a){y()?h.parent.dialogr.updateDialogResult(a):(z=null,t(a)?z=a:(G=a,z=function(){return G}))},isOpen:function(){return e?!0:!1},disableButton:function(a){if(y())h.parent.dialogr.disableButton(a);else if(e.options.buttons){var c=n(e.options.buttons),b;for(b=0;b<c.length;b+=1){var d=e.options.buttons[c[b]]._runtime.elm;
k(a)&&a!==c[b]||(r(d,{disabled:"disabled"}),w(d,"disabled"))}}},enableButton:function(a){if(y())h.parent.dialogr.enableButton(a);else if(e.options.buttons){var c=n(e.options.buttons),b;for(b=0;b<c.length;b+=1){var d=e.options.buttons[c[b]]._runtime.elm;k(a)&&a!==c[b]||(r(d,{disabled:null}),r(d,{"class":null}))}}},click:function(a){if(y())return h.parent.dialogr.click(a);if(e.options.buttons){var c=n(e.options.buttons),b;for(b=0;b<c.length;b+=1){var d=e.options.buttons[c[b]]._runtime.elm;k(a)&&a!==
c[b]||d.click()}}}}}(window);